name: Model Architecture Checks

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision torchsummary pytest pytest-html
        
    - name: Run tests
      run: |
        pytest test_model_architecture.py -v --html=test-results.html --self-contained-html
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results.html
        retention-days: 90
        
    - name: Update README with test results
      if: always()
      run: |
        # Capture the test results
        echo "## Latest Test Results" > test_results.md
        echo "\`\`\`" >> test_results.md
        pytest test_model_architecture.py -v >> test_results.md
        echo "\`\`\`" >> test_results.md
        
        # Update README.md with test results
        cat test_results.md >> README.md